Vramp_amplitude: -0.02
Vramp_duration: 10
cclamp_end: 50
cclamp_start: -50
cclamp_step: 10
cell_R_increase: 0.3
cell_distance: 20
cell_type: Plate
current_protocol: true
custom_protocol: false
gigaseal_R: 1000
gigaseal_min_delta_R: 15
holding_protocol: false
max_R: 25000000.0
max_R_increase: 1000000.0
max_access_R: 50000000.0
max_cell_R: 300000000.0
max_distance: 30
min_R: 2000000.0
min_cell_C: 5.0e-12
mode: Classic
pressure_near: 45
pressure_ramp_duration: 1.15
pressure_ramp_increment: -5
pressure_ramp_max: -30
pressure_sealing: -40.0
pulse_pressure_break_in: -345
seal_deadline: 150
seal_min_time: 15
voltage_protocol: true
zap: true
